INSERT INTO product(id, name, category, price) VALUES('100', 'Samsung S8', 'Mobile', '75000');
INSERT INTO product(id, name, category, price) VALUES('101', 'Realme 6', 'Mobile', '12000');
INSERT INTO product(id, name, category, price) VALUES('200', 'Usha Fan', 'Fan', '1100');
INSERT INTO product(id, name, category, price) VALUES('201', 'Orient Fan', 'Fan', '1200');
INSERT INTO product(id, name, category, price) VALUES('300', 'Dell Vostro', 'Laptop', '79000');
INSERT INTO product(id, name, category, price) VALUES('301', 'Lenovo 441', 'Laptop', '88000');
INSERT INTO product(id, name, category, price) VALUES('400', 'IFB Washer', 'Washing Machine', '25000');
INSERT INTO product(id, name, category, price) VALUES('401', 'Siemens', 'Washing Machine', '3300');
INSERT INTO product(id, name, category, price) VALUES('500', 'Redmi 8', 'Mobile', '7000');
INSERT INTO product(id, name, category, price) VALUES('501', 'Redmi 8', 'Mobile', '9000');
INSERT INTO product(id, name, category, price) VALUES('502', 'Samsung M30', 'Mobile', '13000');
INSERT INTO product(id, name, category, price) VALUES('503', 'Panasonic Eluga', 'Mobile', '9000');
INSERT INTO product(id, name, category, price) VALUES('504', 'Nokia 7', 'Mobile', '12000');