server:
  port: 6060

spring:
  data:
    rest:
      base-path: /sboot-restapi/api
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/springboot"
    username: ranjith
    password: Sekar@123
    
logging:
  file:
    name: logs/app-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    jbr.sboot: DEBUG
    org.hibernate: ERROR
      
cors:
  domain: "http://localhost:4200"
  headers: "origin,accept,x-requested-with,content-type,access-control-request-method,access-control-request-headers,authorization,cache-control,expires,pragma"
  methods: "PUT,DELETE,POST,GET,OPTIONS,PATCH,HEAD"